#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/s5e8535-common

PRODUCT_COPY_FILES += \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/SoundBoosterParam.txt:$(TARGET_COPY_OUT_VENDOR)/etc/SoundBoosterParam.txt \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/beauty/settings.dat:$(TARGET_COPY_OUT_VENDOR)/etc/beauty/settings.dat \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/btcon.json:$(TARGET_COPY_OUT_VENDOR)/etc/btcon.json \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/android.hardware.drm-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.widevine.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.samsung.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/cass.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cass.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/init.baseband.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.baseband.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/init.fingerprint.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fingerprint.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/init.sensorhub.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.sensorhub.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/secaudiohalaidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/secaudiohalaidl.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/teegris.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/teegris.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/vaultkeeper_common.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vaultkeeper_common.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.camera.provider-service_64.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss-service.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/vendor.samsung.hardware.thermal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.thermal@1.0-service.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/init/wifi_slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_slsi.rc \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/mercury.json:$(TARGET_COPY_OUT_VENDOR)/etc/mercury.json \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/mtu-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtu-conf.xml \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/mvno_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mvno_list.xml \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/pdpcnt-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pdpcnt-conf.xml \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/plmn_delta_hktw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_hktw.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/plmn_delta_ltn.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_ltn.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/plmn_se13_prebuilt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13_prebuilt.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/sec_audio_volume_curve.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sec_audio_volume_curve.xml \
    vendor/samsung/s5e8535-common/proprietary/vendor/etc/wifi/indoorchannel.info:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/indoorchannel.info \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/OD_V2.4.2_06_30_QVGA_RICE_VRA_RGB1P.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V2.4.2_06_30_QVGA_RICE_VRA_RGB1P.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/OD_V2.5.1_06_30_VGA_RICE_VRA_RGB1P.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V2.5.1_06_30_VGA_RICE_VRA_RGB1P.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/SetMultiCalInfo.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SetMultiCalInfo.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/SoundAlive.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundAlive.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/a2dpcom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a2dpcom.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/abox_system.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_system.conf \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/abox_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/abox_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.conf \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/avsyncmix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/avsyncmix.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/camera_tilt_calibration_info_1_4:$(TARGET_COPY_OUT_VENDOR)/firmware/camera_tilt_calibration_info_1_4 \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/cs40l26.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.wmfw \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/default_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.flm.cfg.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/dolby.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dolby.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/listenbackeffect.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/listenbackeffect.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/sb_ll.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_ll.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/sb_music.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_music.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/sb_others.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_others.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/sectiongraph_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sectiongraph_tplg.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/secure_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/secure_configuration.flm.cfg.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/volumemonitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volumemonitor.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/wifi/mx140.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140.bin \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/wifi/mx140_common.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_common.hcf \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/wifi/mx140_wlan_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_sw.hcf \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/wifi/mx140_wlan_t_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_t_sw.hcf \
    vendor/samsung/s5e8535-common/proprietary/vendor/firmware/wifi/slsi_reg_database.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/slsi_reg_database.bin

PRODUCT_PACKAGES += \
    libGLES_mali \
    audio.primary.s5e8535 \
    audio.sec_primary.default \
    gatekeeper.s5e8535 \
    libsecaudiohal_aidl \
    vulkan.mali \
    libExtIRTA \
    libSamsungPostProcessConvertor \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    lib_SamsungRec_07010 \
    lib_SoundAlive_SRC384_ver320 \
    lib_profiler \
    lib_soundaliveresampler \
    libaboxpcmdump \
    libalsautils_sec \
    libaudio-ril \
    libaudioparamupdate \
    libaudioproxy2 \
    libaudioroute_vendor \
    libdatamod \
    libegis_fp_normal_sensor_test \
    libengmode_client \
    libfloatingfeature \
    libgf_in_system_lib \
    liblastaboxmsg \
    liboemcrypto \
    libprofileparamstorage \
    libqfp_sensortest \
    librecordalive \
    libril_sem \
    libsamsungcamerahal \
    libsamsungcamerahalutils \
    libsamsungcamerahwl_impl \
    libsec-ril \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecaudiolevel \
    libsecnativefeature \
    libsecril-client \
    libsehbluetooth_audio_session_aidl \
    libsemnativecarrierfeature \
    libsfp_sensor \
    libsfp_teegw \
    libskeymint10device \
    libskeymint_cli \
    libspatializerparamstorage \
    libspeakercalibration \
    libstork_shared \
    libsynaFpSensorTestNwd \
    libteecl \
    libtinyalsa_vendor \
    libuuid_vendor \
    libvkmanager_vendor \
    libvkservice \
    libwrappergps \
    libwvaidl \
    vendor.samsung.hardware.audio-V1-ndk \
    vendor.samsung.hardware.audio@1.0 \
    vendor.samsung.hardware.biometrics.fingerprint-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-V1-ndk \
    vendor.samsung.hardware.camera.device-V1-ndk \
    vendor.samsung.hardware.camera.provider-V1-ndk \
    vendor.samsung.hardware.gnss-V3-ndk \
    vendor.samsung.hardware.keymint-V2-ndk \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    manifest_android.hardware.drm-service.widevine.xml \
    secaudiohalaidl_manifest.xml \
    vendor.samsung.hardware.camera.provider-service.xml \
    vendor.samsung.hardware.radio.exclude.slsi.xml \
    vendor.samsung.hardware.radio_manifest_2_33.xml \
    vendor.samsung.hardware.sehradio_manifest_2_33.xml \
    vendor.samsung.hardware.thermal@1.0-manifest.xml \
    cass \
    android.hardware.drm-service.widevine \
    android.hardware.security.keymint-service.samsung \
    gps \
    rild \
    secaudiohalaidl \
    vendor.samsung.hardware.camera.provider-service_64 \
    vendor.samsung.hardware.gnss-service \
    tzdaemon \
    tzts_daemon \
    vaultkeeperd

PRODUCT_PACKAGES += \
    vendor_lib64_libOpenCL_so \
    vendor_lib64_libOpenCL_so_1 \
    vendor_lib64_libOpenCL_so_1_1
